-- migrate:up
CREATE TABLE "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "first_name" varchar,
    "last_name" varchar,
    "email" varchar
);

-- migrate:down
DROP TABLE "users";

