// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Album struct {
	ID       int64
	ArtistID int64
	Name     string
	Cover    string
}

type Artist struct {
	ID    int64
	Name  string
	Image sql.NullString
}

type Person struct {
	ID        int32
	FirstName string
	LastName  string
	FullName  string
	Age       int32
	Salary    pgtype.Numeric
	StartDate time.Time
	Phone     pgtype.JSON
	Languages []string
}

type Song struct {
	ID       int64
	AlbumID  int64
	ArtistID int64
	Title    string
	Length   float64
	Track    sql.NullInt32
	Path     string
	Mtime    int32
}

type Test struct {
	ID         int64
	Uuid       uuid.NullUUID
	Varchar    sql.NullString
	Text       sql.NullString
	Int        sql.NullInt32
	Bigint     sql.NullInt64
	Float      sql.NullFloat64
	Double     sql.NullFloat64
	Decimal    pgtype.Numeric
	Boolean    sql.NullBool
	Inet       pgtype.Inet
	Macaddr    pgtype.Macaddr
	Json       pgtype.JSON
	Jsonb      pgtype.JSONB
	Xml        interface{}
	Date       sql.NullTime
	Time       sql.NullTime
	Timez      sql.NullTime
	Timestamp  sql.NullTime
	Timestampz sql.NullTime
}
