// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: people.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgtype"
)

const createPerson = `-- name: CreatePerson :exec
INSERT INTO people 
    (first_name, last_name, full_name, age, salary, start_date, phone, languages)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreatePersonParams struct {
	FirstName string
	LastName  string
	FullName  string
	Age       int32
	Salary    pgtype.Numeric
	StartDate time.Time
	Phone     pgtype.JSON
	Languages []string
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) error {
	_, err := q.db.Exec(ctx, createPerson,
		arg.FirstName,
		arg.LastName,
		arg.FullName,
		arg.Age,
		arg.Salary,
		arg.StartDate,
		arg.Phone,
		arg.Languages,
	)
	return err
}
