// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: users.sql

package pgsql

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" ("first_name", "last_name", "email")
VALUES ($1, $2, $3)
RETURNING "id"
`

type CreateUserParams struct {
	FirstName sql.NullString
	LastName  sql.NullString
	Email     sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, arg.FirstName, arg.LastName, arg.Email)
	var id int64
	err := row.Scan(&id)
	return id, err
}
